const model = {
    dealTo: "dealer",
    splitStatus: "disabled",
    gameStatus: "disabled",
    dealStatus: "",
    winText: "",
    splitText: "",
    isBusted: false,
    isSplitBusted: false,
    isSplit: false,
    splitBusted: false,
    dealerValue: 0,
    playerValue: 0,
    splitValue: 0,
    dealerCards: [],
    playerCards: [],
    splitCards: [],
    deck: [
        {
            value: 1,
            display: "🂡",
            color: "black",
            isAce: true,
        },
        {
            value: 2,
            display: "🂢",
            color: "black",
            isAce: false,
        },
        {
            value: 3,
            display: "🂣",
            color: "black",
            isAce: false,
        },
        {
            value: 4,
            display: "🂤",
            color: "black",
            isAce: false,
        },
        {
            value: 5,
            display: "🂥",
            color: "black",
            isAce: false,
        },
        {
            value: 6,
            display: "🂦",
            color: "black",
            isAce: false,
        },
        {
            value: 7,
            display: "🂧",
            color: "black",
            isAce: false,
        },
        {
            value: 8,
            display: "🂨",
            color: "black",
            isAce: false,
        },
        {
            value: 9,
            display: "🂩",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🂪",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🂫",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🂭",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🂮",
            color: "black",
            isAce: false,
        },
        {
            value: 1,
            display: "🂱",
            color: "red",
            isAce: true,
        },
        {
            value: 2,
            display: "🂲",
            color: "red",
            isAce: false,
        },
        {
            value: 3,
            display: "🂳",
            color: "red",
            isAce: false,
        },
        {
            value: 4,
            display: "🂴",
            color: "red",
            isAce: false,
        },
        {
            value: 5,
            display: "🂵",
            color: "red",
            isAce: false,
        },
        {
            value: 6,
            display: "🂶",
            color: "red",
            isAce: false,
        },
        {
            value: 7,
            display: "🂷",
            color: "red",
            isAce: false,
        },
        {
            value: 8,
            display: "🂸",
            color: "red",
            isAce: false,
        },
        {
            value: 9,
            display: "🂹",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🂺",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🂻",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🂽",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🂾",
            color: "red",
            isAce: false,
        },
        {
            value: 1,
            display: "🃁",
            color: "red",
            isAce: true,
        },
        {
            value: 2,
            display: "🃂",
            color: "red",
            isAce: false,
        },
        {
            value: 3,
            display: "🃃",
            color: "red",
            isAce: false,
        },
        {
            value: 4,
            display: "🃄",
            color: "red",
            isAce: false,
        },
        {
            value: 5,
            display: "🃅",
            color: "red",
            isAce: false,
        },
        {
            value: 6,
            display: "🃆",
            color: "red",
            isAce: false,
        },
        {
            value: 7,
            display: "🃇",
            color: "red",
            isAce: false,
        },
        {
            value: 8,
            display: "🃈",
            color: "red",
            isAce: false,
        },
        {
            value: 9,
            display: "🃉",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🃊",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🃋",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🃍",
            color: "red",
            isAce: false,
        },
        {
            value: 10,
            display: "🃎",
            color: "red",
            isAce: false,
        },
        {
            value: 1,
            display: "🃑",
            color: "black",
            isAce: true,
        },
        {
            value: 2,
            display: "🃒",
            color: "black",
            isAce: false,
        },
        {
            value: 3,
            display: "🃓",
            color: "black",
            isAce: false,
        },
        {
            value: 4,
            display: "🃔",
            color: "black",
            isAce: false,
        },
        {
            value: 5,
            display: "🃕",
            color: "black",
            isAce: false,
        },
        {
            value: 6,
            display: "🃖",
            color: "black",
            isAce: false,
        },
        {
            value: 7,
            display: "🃗",
            color: "black",
            isAce: false,
        },
        {
            value: 8,
            display: "🃘",
            color: "black",
            isAce: false,
        },
        {
            value: 9,
            display: "🃙",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🃚",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🃛",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🃝",
            color: "black",
            isAce: false,
        },
        {
            value: 10,
            display: "🃞",
            color: "black",
            isAce: false,
        },
    ]
}